cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'autojump'
brew 'coreutils'
brew 'git'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'kubectl'
brew 'kubectx'
brew 'libcaca'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'puma/puma/puma-dev'
brew 'python'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'wget'
brew 'yarn'
brew 'youtube-dl'

cask 'adoptopenjdk'
cask 'caffeine'
cask 'firefox'
cask 'google-cloud-sdk'
cask 'google-featured-photos'
cask 'handbrake'
cask 'iterm2'
cask 'steam'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
